---
openapi: 3.0.0
info:
  title: udaconnect-api
  description: All APIs for Udaconnect project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/PRATHYUM97/Udaconnect-api/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /persons:
    post:
      tags:
      - Persons
      description: creating Person
      responses:
        "200":
          description: created Person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSchema'
  /persons/:
    get:
      tags:
      - Persons
      description: get all persons
      responses:
        "200":
          description: all persons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSchema'
  /persons/{person_id}:
    get:
      tags:
      - Persons
      description: get person by id
      parameters:
      - name: person_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: found person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSchema'
  /locations:
    get:
      tags:
      - Locations
      description: get all locations
      responses:
        "200":
          description: all locations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationSchema'
    post:
      tags:
      - Locations
      description: creating location
      responses:
        "200":
          description: location created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationSchema'
  /locations/{location_id}:
    get:
      tags:
      - Locations
      description: get location by id
      parameters:
      - name: location_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationSchema'
  /persons/{person_id}/connection:
    get:
      tags:
      - Connection
      description: return connections by start and end date with specific person id
      parameters:
      - name: start_date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: object
      - name: end_date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: object
      - name: distance
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: object
      - name: person_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionSchema'
components:
  schemas:
    LocationSchema:
      type: object
      properties:
        id:
          type: integer
        person_id:
          type: integer
        longitude:
          type: string
        latitude:
          type: string
        creation_time:
          type: object
    PersonSchema:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        company_name:
          type: string
    ConnectionSchema:
      type: object
      properties:
        location:
          type: object
        person:
          type: object